FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

COPY tsconfig.json eslint.config.js ./
COPY src ./src

EXPOSE 3001

CMD ["npm", "run", "dev"]
